### ISSUE TITLE
Completions for other binaries?

### ISSUE THREAD

**Issue by pheanex** [dysosmus/ansible-completion#14]
There are a few more ansible tools. Namely:
* ansible-doc
* ansible-galaxy
* ansible-playbook
* ansible-pull
* ansible-vault

Would you like to implement completion for those as well in this repo or at least accept pull-requests?

**Comment by dysosmus** [comment]
If there is acceptable pulls requests for these completions I will merge it,
but I do not plan to do the implementation by myself at the moment.

**Comment by pheanex** [comment]
ok, i implemented a basic version for all of them -> see PR

**Comment by dysosmus** [comment]
I have merged your PR, thanks for the contribution, it's a nice to have completions on others binaires.
