### ISSUE TITLE
Dir `~/bash_completion` is not automatically loaded, File `~/.bash_completion` is.

### ISSUE THREAD

**Issue by ava-dylang** [dysosmus/ansible-completion#17]
I wanted to point out that the installation steps for a user-defined bash completion

A) direct users to make a non hidden directory for thier user configuration, which breaks the norm and
B) doesn't actually get autoloaded by the bash shell.

However, according to http://serverfault.com/q/506612/210994

a user can make a file `~/.bash_completion` and append to that file with the completions they want.

Or even better, make a directory `~/.bash_completion.d/` and populate the `~/.bash_completion` file with the body:

```
~/.bash_completion
#!/usr/bin/env bash

if [ -d "$HOME/.bash_completion.d" ]; then
    for filename in "$HOME/.bash_completion.d/*"; do
        source $filename
    done
fi
```

Any file placed in `~/.bash_completion.d/` will be loaded.

This utilizes the existing bash autoload, And leaves the config files as hidden files to follow precedent.

**Comment by dysosmus** [comment]
Well it's all depending on how you want to use it.
I will make some updates to the instructions to reflect your comment, but the user should do as I want.
