### ISSUE TITLE
Scope of this project

### ISSUE THREAD

**Issue by thokari** [dysosmus/ansible-completion#20]
Hi, 
I wanted to learn about bash completion by writing something like this, for ansible-playbook.
In particular, I wanted to make it so, that when you provide a parameter for the inventory, for example `-i inventory/my-inventory` and then you add the `--limit` parameter, it would complete the possible parameter values according to what is in that inventory.
Would you consider that a suitable addition?
Not sure how hard it is though... ;)

**Comment by dysosmus** [comment]
Hi, picking up the `-i` or `—inventory` value and then autocompleting with the data found in the inventory file is the current behaviour.
However that only happening when auto-completing with the `ansible` command.
It shouldn’t be crazy hard to reuse https://github.com/dysosmus/ansible-completion/blob/master/ansible-completion.bash#L25 to do the same for `ansible-playbook` or any other `ansible-*`.
You are, of course, welcome to do it. :)
